# Node.js

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'SnykConDemo'
    testType: 'app'
    monitorWhen: 'never'
    failOnIssues: true
    projectName: 'snykAzp'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo "My Name is Aneh"
      echo PWD
      echo date
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

